### ISSUE TITLE
Release 0.8.1

### ISSUE THREAD

**Issue by milliondreams** [tuplejump/calliope#14]
- Support for Spark 0.8.1
- Upgrade to Cassandra 1.2.12

**Comment by milliondreams** [comment]
@tuplejump/calliopeusers @tuplejump/mentionllc @tuplejump/ateam 

Announcing release 0.8.1-EA with support for Spark 0.8.1 and using Cassandra 1.2.12

**Comment by bobbych** [comment]
Hi Rohit,
              We started using it, basically we are running spark worker
process on cassandra nodes that talk to spark master. Also trying to add
shark, however, when we try to use shark , it is not running in cluster
mode. , it starts with message NO_HADOOP_Home set. Is there a way to bypass
this, i know we don't require Hadoop for this. what should i use for
HADOOP_HOME

Thank you
Bobby
