### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/cassandra/exceptions/ConfigurationException

### ISSUE THREAD

**Issue by lvicentesanchez** [tuplejump/calliope#31]
I'm trying to use the spark 1.0.0 SNAPSHOT (0.9.4-EA-SNAPSHOT) but I'm getting this error:

java.lang.NoClassDefFoundError: org/apache/cassandra/exceptions/ConfigurationException

The only way I could solved it was by adding,

"org.apache.cassandra" % "cassandra-all"    % "2.0.8"

as a dependency.

**Comment by milliondreams** [comment]
Yes, cassandra-all is needed for Calliope

**Comment by lvicentesanchez** [comment]
Shouldn't that be a transitive dependency?

**Comment by milliondreams** [comment]
We don't make it a transient dependency so you can just add the one corresponding to your Cassandra version. Do you think we should make it a transient dependency?

**Comment by lvicentesanchez** [comment]
Hum... either it should be a transitive dependency, as binary compatibility is granted for the same cassandra release (i.e. 2.0.2 is binary compatible with 2.0.9 and users could bump to 2.0.9 if desired); or it should be made explicit that you need to add the cassandra dependency yourself, to avoid people thing there is a problem with the release... :)

**Comment by lvicentesanchez** [comment]
Sorry I have just checked the website... I missed the "Getting started" section... :)
