### ISSUE TITLE
How do i run the specs?

### ISSUE THREAD

**Issue by pezra** [tuplejump/calliope#33]
I tried `sbt test` which does run the tests but they seem to be expecting some keyspaces and tables and such. Is there a script to create those?

**Comment by milliondreams** [comment]
@pezra You'll need to start cassandra and load the test data prior to running the tests.

The scripts are here - https://github.com/tuplejump/calliope/tree/develop/src/test/resources

You'll need to run datascript.cli using the old cli and the cql3test.cql using cqlsh.

**Comment by pezra** [comment]
thanks!
