### ISSUE TITLE
issue when using calliope on spark 1.0

### ISSUE THREAD

**Issue by bobbych** [tuplejump/calliope#36]
error: bad symbolic reference. A signature in RichByteBuffer.class refers to term time
in value org.joda which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling RichByteBuffer.class.

**Comment by milliondreams** [comment]
Please add these 2 jars to the application classpath using addJar/Submit.
- http://search.maven.org/remotecontent?filepath=com/github/nscala-time/nscala-time_2.10/1.0.0/nscala-time_2.10-1.0.0.jar
- http://search.maven.org/remotecontent?filepath=joda-time/joda-time/2.3/joda-time-2.3.jar

These are new dependencies in the snapshot build.

**Comment by bobbych** [comment]
Thanks Rohit that worked but still having below issue

scala> val cas = CasBuilder.cql3.withColumnFamily("spark", "search").onHost("x.x.x.x.x")
cas: com.tuplejump.calliope.Cql3CasBuilder = com.tuplejump.calliope.Cql3CasBuilder@3b4d67

scala> val rdd = sc.cql3Cassandra[Map[String, String], Map[String, String]](cas)
<console>:22: error: erroneous or inaccessible type
       val rdd = sc.cql3Cassandra[Map[String, String], Map[String, String]](cas)

**Comment by milliondreams** [comment]
Have you imported RichByteBuffer._?

If yes, can you give me the script that is resulting in this  error?

**Comment by bobbych** [comment]
Hi Rohit,
              I am just using spark shell and have all required files in spark class path
import com.tuplejump.calliope.utils.RichByteBuffer._
import com.tuplejump.calliope.Implicits._
import com.tuplejump.calliope.CasBuilder
val cas = CasBuilder.cql3.withColumnFamily("spark", "search").onHost("cass1")
val rdd = sc.cql3Cassandra[Map[String, String], Map[String, String]]

**Comment by milliondreams** [comment]
Shouldn't this, 

``` scala

val rdd = sc.cql3Cassandra[Map[String, String], Map[String, String]]

```

infact be, you are missing passing **cas** to the method

``` scala

val rdd = sc.cql3Cassandra[Map[String, String], Map[String, String]](cas)

```

**Comment by bobbych** [comment]
Actually I did that it's missing from snippets. This is only happening in spark 1.0 no issue in 0.9

**Comment by milliondreams** [comment]
Just to confirm, are you using the the snapshot build - **0.9.4-EA-SNAPSHOT** with Spark 1.0.0? and you have the calliope-macros jar on the classpath too . . .

These are the jars you should have -
- https://oss.sonatype.org/service/local/repositories/snapshots/content/com/tuplejump/calliope_2.10/0.9.4-EA-SNAPSHOT/calliope_2.10-0.9.4-EA-SNAPSHOT.jar
- https://oss.sonatype.org/service/local/repositories/snapshots/content/com/tuplejump/calliope-macros_2.10/0.9.4-EA-SNAPSHOT/calliope-macros_2.10-0.9.4-EA-SNAPSHOT.jar

And which is the build of spark that you use? Is it with Hadoop 1.x or 2.x?

**Comment by bobbych** [comment]
Ah.. that might be it I am missing macros jar. I will try with this
Thank you !!
