### ISSUE TITLE
cacheTable doesn't work

### ISSUE THREAD

**Issue by bobbych** [tuplejump/calliope#40]
sparksql context caching looks like is not working, i am executing below code

val cc = new org.apache.spark.sql.CassandraAwareSQLContext(sc)
cc.cacheTable("demo.search")
cc.sql("select \* from demo.search").count()

every time i try to query i getting CassandraTableScan

However, if it do same in hive context it seems to work it now returning plan InMemoryColumnarTableScan

**Comment by milliondreams** [comment]
@bobbych 
that is a bug... We will fix it in the next release.

**Comment by bobbych** [comment]
@milliondreams thanks, i had another question will open a different issue
